### ISSUE TITLE
Unicycler/SPades Error

### ISSUE THREAD

**Issue by ufuomababatunde** [fmaguire/arete#10]
## Check Documentation

I have checked the following places for your error:

- [ ] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [ ] [nf-core/arete pipeline documentation](https://nf-co.re/nf-core/arete/usage)

## Description of the bug

Error in Unicycler part due to SPades

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: 
`nextflow run arete --input_sample_table samplesheet.csv --reference_genome 00_refGenome/NZ_CP043953.1.fasta  -profile docker`
2. See error: 
`Command Exit Status: 1`
![image](https://user-images.githubusercontent.com/70242638/211572241-c6e2d9e7-8067-4e62-8302-414b144a709a.png)

## Log files

Have you provided the following extra information/files:

- [ ] The command used to run the pipeline
`nextflow run arete --input_sample_table samplesheet.csv --reference_genome 00_refGenome/NZ_CP043953.1.fasta  -profile docker`

- [ ] The `.nextflow.log` file 
[nextflow.log](https://github.com/fmaguire/arete/files/10383420/nextflow.log)

## System

- Hardware: 
- Executor: 
- OS: 
- Version 
![image](https://user-images.githubusercontent.com/70242638/211573336-b9c871ad-887e-41bf-a092-618b5baa4796.png)

## Nextflow Installation

- Version: 22.10.4

## Container engine

- Engine: Docker
- version: 20.10.21
- Image tag:

**Comment by fmaguire** [comment]
Hi, the main release for this workflow is available at https://github.com/beiko-lab/arete
Please try that and test using the test workflow listed in the documentation.
